name: Update k8s deployments
description: Reusable action for updating k8s deployments

inputs:
  files-to-update:
    description: "A space-separated list of files to update"
    required: true
  text-prefix:
    description: "A regular expression to match in the files when looking for the version to update"
    required: false
  component:
    description: "Which component to update"
    required: true
  push-token:
    description: "The Github token needed to create PRs"
    required: true

runs:
  using: composite
  steps:
    - name: Check out k8s repository
      uses: actions/checkout@v4
      with:
        repository: dfinity-ops/k8s
        token: ${{ inputs.push-token }}
        ref: main
        fetch-depth: 2
        path: k8s
    - name: "Create rollout commit with updated container images"
      id: "create-rollout-commit"
      env:
        PUSH_TOKEN: ${{ inputs.push-token }}
        FILES_TO_UPDATE: ${{ inputs.files-to-update }}
        COMPONENT: ${{ inputs.component }}
      shell: bash
      run: |
        set -eExu -o pipefail
        cd k8s

        git config user.email "idx@dfinity.org"
        git config user.name "IDX Automation"
        SOURCE_BRANCH="${{ github.head_ref || github.ref_name }}"
        K8S_REPO_BRANCH="$( echo "update-$(basename $GITHUB_REPOSITORY)-$COMPONENT-images-from-$SOURCE_BRANCH" | tr -cd '[:alnum:]._-' )"
        base_regex='${{ inputs.text-prefix }}'

        if [ -n "$base_regex" ]
        then
          base_regex="(${base_regex})"
        else
          base_regex="(.+:)"
        fi

        git checkout -b "${K8S_REPO_BRANCH}"

        # Update the refs in the requested files.
        # Refs are assumed to be named sha-[0-9a-f]+.
        prev_commit=$(sed -rn 's~(.*)'"$base_regex"'sha-([a-f0-9]{40}).*~\3~p' $FILES_TO_UPDATE | head -1)
        sed -ri 's~(.*)'"$base_regex"'sha-([a-f0-9]{40})~\1\2sha-'"${GITHUB_SHA}"'~' $FILES_TO_UPDATE

        # commit changes if there are any
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        # Push changes and create a new merge request
        git commit -m "New $COMPONENT release from $SOURCE_BRANCH branch"
        git push \
          --force --set-upstream origin "${K8S_REPO_BRANCH}" || \
          git push --force --set-upstream origin "${K8S_REPO_BRANCH}"

        echo "k8s_branch=$K8S_REPO_BRANCH" >> $GITHUB_OUTPUT
        echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
        echo "previous_ref=$prev_commit" >> $GITHUB_OUTPUT
        echo "current_ref=$GITHUB_SHA" >> $GITHUB_OUTPUT
    - name: "Create PR to roll out with updated container images"
      id: create-rollout-pr
      if: ${{ steps.create-rollout-commit.outputs.k8s_branch != '' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.push-token }}
        script: |
          const owner = 'dfinity-ops';
          const repo = 'k8s';
          const base = 'main';
          const head = '${{ steps.create-rollout-commit.outputs.k8s_branch }}';
          const title = 'Rollout of ${{ inputs.component }} from ${{ github.repository }}@${{ github.head_ref || github.ref_name }}';
          const pulls = await github.rest.pulls.list({
            owner: owner,
            repo: repo,
            base: base,
            state: 'open'
          });
          const pulldata = pulls.data.filter((pull) => pull.title == title);
          if (pulldata.length > 0) {
            console.log("Existing PRs:");
            console.log(pulldata);
            var result = await github.rest.pulls.update({
              owner: owner,
              repo: repo,
              pull_number: pulldata[0].number,
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).',
            });
            console.log("Updated pull request " + pulldata[0].number);
            await core.summary
              .addLink('Pull request to roll out ${{ inputs.component }} updated.', 'https://github.com/dfinity-ops/k8s/pull/' + pulldata[0].number)
              .write();
            return result;
          } else {
            var result = await github.rest.pulls.create({
              title: title,
              owner: owner,
              repo: repo,
              head: head,
              base: base,
              maintainer_can_modify: true,
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).'
            });
            console.log("Created pull request:");
            console.log(result);
            await core.summary
              .addLink('Pull request to roll out ${{ inputs.component }} created.', 'https://github.com/dfinity-ops/k8s/pull/' + result.data.number)
              .write();
            return result;
          }
