name: Update k8s deployments
description: Reusable action for updating k8s deployments

inputs:
  files-to-update:
    description: "A space-separated list of files to update"
    required: true
  component:
    description: "Which component to update"
    required: true
  push-token:
    description: "The Github token needed to create PRs"
    required: true

runs:
  using: composite
  steps:
    - name: "Create rollout commit with updated container images"
      id: "create-rollout-commit"
      env:
        PUSH_TOKEN: ${{ inputs.push-token }}
        FILES_TO_UPDATE: ${{ inputs.files-to-update }}
        COMPONENT: ${{ inputs.component }}
      shell: bash
      run: |
        set -eExu -o pipefail

        tmpdir=$(mktemp)
        trap 'rm -rf "$tmpdir"' EXIT

        # checkout branch
        git clone --depth 10 --branch "main" "https://${PUSH_TOKEN}@github.com/dfinity-ops/k8s.git"

        cd k8s
        git config user.email "idx@dfinity.org"
        git config user.name "IDX Automation"
        SOURCE_BRANCH="${{ github.head_ref || github.ref_name }}"
        K8S_REPO_BRANCH="update-dre-airflow-$COMPONENT-images-from-$SOURCE_BRANCH"

        git checkout -b "${K8S_REPO_BRANCH}"

        # Update the refs in the requested files.
        # Refs are assumed to be named sha-[0-9a-f]+.
        prev_commit=$(sed -rn 's~(.+):sha-([a-f0-9]{40})~\2~p' $FILES_TO_UPDATE | head -1)
        sed -ri 's~(.+):sha-([a-f0-9]{40})~\1:sha-'"${GITHUB_SHA}"'~' $FILES_TO_UPDATE

        # commit changes if there are any
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi

        # Push changes and create a new merge request
        git commit -m "New $COMPONENT release from $SOURCE_BRANCH branch"
        git push \
          --force --set-upstream origin "${K8S_REPO_BRANCH}" || \
          git push --force --set-upstream origin "${K8S_REPO_BRANCH}"

        echo "k8s_branch=$K8S_REPO_BRANCH" >> $GITHUB_OUTPUT
        echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
        echo "previous_ref=$prev_commit" >> $GITHUB_OUTPUT
        echo "current_ref=$GITHUB_SHA" >> $GITHUB_OUTPUT
    - name: "Create PR to roll out with updated container images"
      id: create-rollout-pr
      if: ${{ steps.create-rollout-commit.outputs.k8s_branch != '' }}
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        github-token: ${{ inputs.push-token }}
        script: |
          const owner = 'dfinity-ops';
          const repo = 'k8s';
          const base = 'main';
          const head = '${{ steps.create-rollout-commit.outputs.k8s_branch }}';
          const pulls = await github.rest.pulls.list({
            owner: owner,
            repo: repo,
            base: base,
            head: head
          });
          if (pulls.data.length > 0) {
            const result = await github.rest.pulls.update({
              owner: owner,
              repo: repo,
              pull_number: pulls[0]["number"],
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).',
            });
          } else {
            const result = await github.rest.pulls.create({
              title: '[nomrbot] - New ${{ inputs.component }} release from ${{ github.repository }}',
              owner: owner,
              repo: repo,
              head: head,
              base: base,
              maintainer_can_modify: true,
              body: 'Updating container images to incorporate [these changes](https://github.com/${{ github.repository }}/compare/${{ steps.create-rollout-commit.outputs.previous_ref }}..${{ steps.create-rollout-commit.outputs.current_ref }}).'
            });
          }
          return result;
