name: Airflow content QA
on:
  pull_request:
    paths-ignore:
      - airflow-content-syncer/**
      - airflow-customized/**
      - rollout-dashboard/**
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-airflow-content:
    name: Test Airflow content
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: ./.github/workflows/test
