name: Airflow content QA
on:
  pull_request:
    paths-ignore:
      - airflow-content-syncer/**
      - airflow-customized/**
      - rollout-dashboard/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    name: Run tests on Airflow content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test"
        uses: ./.github/workflows/test
