name: Airflow content syncer container
on:
  push:
    branches:
      - "main"
    paths:
      - airflow-content-syncer/**
      - .github/**
  pull_request:
    paths:
      - airflow-content-syncer/**
      - .github/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-airflow-content-syncer:
    name: Build Airflow content syncer container
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    # This image is based on ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/publish
        name: Create airflow-content-syncer container
        with:
          container: airflow-content-syncer
          context: airflow-content-syncer
          registry-token: ${{ secrets.GITHUB_TOKEN }}
  publish-airflow-content-syncer:
    name: Publish Airflow content syncer container
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # This image is based on ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/publish
        name: Create and publish airflow-content-syncer container
        with:
          container: airflow-content-syncer
          context: airflow-content-syncer
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          publish: true
          push-token: ${{ secrets.K8S_API_TOKEN }}
          files-to-update: bases/apps/airflow/core/afvalues.yaml bases/apps/airflow/core/patches/job-pod-init-container.yaml
          text-prefix: "airflow-content-syncer:"
