name: Airflow customized container
on:
  push:
    branches:
      - "main"
    paths:
      - airflow-customized/**
      - .github/**
  pull_request:
    paths:
      - airflow-customized/**
      - .github/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-airflow-customized:
    name: Build customized Airflow container
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    # This image is based on ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/publish
        name: Create airflow-customized container
        with:
          container: airflow-customized
          context: airflow-customized
          registry-token: ${{ secrets.GITHUB_TOKEN }}
  publish-airflow-customized:
    name: Publish customized Airflow container
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # This image is based on ubuntu:20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/publish
        name: Create and publish airflow-customized container
        with:
          container: airflow-customized
          context: airflow-customized
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          publish: true
          push-token: ${{ secrets.K8S_API_TOKEN }}
          files-to-update: bases/apps/airflow/core/afvalues.yaml
          text-prefix: "defaultAirflowTag: "
